Update to 2024 beta
thedropbears/pycrescendo pull request #3
Opened 2024-01-05 13:54 UTC by outsidermm

Update requirement.txt and Pipfile to use the 2024 version of imported modules. (Not phoenix 6)

2024-01-05 13:57 UTC, outsidermm commented
I'm not sure what to do with the CTRE current version number. I thought the 2024 is now called phoenix6, and we are using that later. If we use the 2023.1.0 CTRE it would have conflict with other dependencies as all the other dependencies it requires are 2023. (obviously)

2024-01-06 00:16 UTC, auscompgeek commented
> I'm not sure what to do with the CTRE current version number. I thought the 2024 is now called phoenix6

We need to update to the 2024 beta version of Phoenix 5 first.

2024-01-06 01:13 UTC, auscompgeek requested changes

2024-01-06 01:13 UTC, auscompgeek commented on requirements.txt
> +robotpy[apriltag,cscore]~=2024.0.0b3
Please update to the latest beta (currently `2024.0.0b4`).

2024-01-06 01:13 UTC, auscompgeek commented on requirements.txt
> +robotpy-ctre~=2024.0.0b1
We should use the latest beta here. There aren't any guarantees older vendor beta libraries will work with newer roboRIO/WPILib betas.

2024-01-06 01:54 UTC, auscompgeek commented on components/chassis.py
> +from utilities.phoenix5 import FALCON_CPR, FALCON_FREE_RPS
Let's not rename our `utilities.ctre` module.

2024-01-06 02:32 UTC, outsidermm commented
Robot moves in sim

2024-01-06 04:12 UTC, james-ward approved these changes

2024-01-06 04:14 UTC, auscompgeek approved these changes

2024-01-06 04:14 UTC, merged